### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by m1ga** [soulglo/ti-alloy-related#5]
Hi,

you still need to push the updated version in order to remove the deprecation warning.

also update the package.json from

~~~
"activationEvents": [
    "ti-alloy-related:openRelated"
  ]
~~~
to

~~~
 "activationCommands": {
    "atom-workspace": ["ti-alloy-related:openRelated"],
    "atom-text-editor": ["ti-alloy-related:openRelated"]
  }
~~~

then it should still run in 1.0!

**Comment by davrosull** [comment]
Thanks @m1ga - updated any published
